In [1]:
import numpy as np
import matplotlib.pyplot as plt

from sysgen import sysgen
from sysid import sysid
from syssim import syssim

In [2]:
# System Data
n = 3
p = 2

# Nominal system:
A_0 = np.array([[0.6, 0.5, 0.4],
                [0, 0.4, 0.3],
                [0, 0, 0.3]])

B_0 = np.array([[1, 0.5],
                [0.5, 1],
                [0.5, 0.5]])

V = np.array([[0, 0, 0],
              [0, 1, 0],
              [0, 0, 1]])  # Modification pattern applied to A_0

U = np.array([[1, 0],
              [0, 0],
              [0, 1]])  # Modification pattern applied to B_0

# Noise levels
sigu = 1
sigw = 1
sigx = 1

# Rollout length
T = 5

# Select FL_solver (Fed_Avg = 0, Fed_Lin = 1)
FL_solver = 0

q = 25  # number of estimations
R = 200  # number of global iterations
s = 1  # fixed system for the error computation

M = [1,5,10,25]
N = 25  # Fixed number of rollouts
epsilon = 0.01  # Fixed dissimilarity

In [3]:
A, B = sysgen(A_0, B_0, V, U, max(M), epsilon)  # Generate similar systems

E_avg = np.zeros((len(M), R))
A

[array([[0.6       , 0.5       , 0.4       ],
        [0.        , 0.40026094, 0.3       ],
        [0.        , 0.        , 0.30026094]]),
 array([[0.6       , 0.5       , 0.4       ],
        [0.        , 0.40529333, 0.3       ],
        [0.        , 0.        , 0.30529333]]),
 array([[0.6       , 0.5       , 0.4       ],
        [0.        , 0.40039946, 0.3       ],
        [0.        , 0.        , 0.30039946]]),
 array([[0.6      , 0.5      , 0.4      ],
        [0.       , 0.4014065, 0.3      ],
        [0.       , 0.       , 0.3014065]]),
 array([[0.6       , 0.5       , 0.4       ],
        [0.        , 0.40871057, 0.3       ],
        [0.        , 0.        , 0.30871057]]),
 array([[0.6       , 0.5       , 0.4       ],
        [0.        , 0.40369426, 0.3       ],
        [0.        , 0.        , 0.30369426]]),
 array([[0.6       , 0.5       , 0.4       ],
        [0.        , 0.40235447, 0.3       ],
        [0.        , 0.        , 0.30235447]]),
 array([[0.6       , 0.5     

In [4]:
# n = A[0].shape[0]
# p = B[0].shape[1]

# Générer les trajectoires du système
X = []
Z = []
W = []
for i in range(len(M)):

    X_i, Z_i, W_i, list_x0 = syssim(A, B, T, N, i, sigu, sigw, sigx)
    X.append(X_i)
    Z.append(Z_i)
    W.append(W_i)

In [5]:
len(A)

25

In [11]:

j=3
s=7
FL_solver=0
Error=sysid(A, B, T, N, M[j], R, sigu, sigx, sigw, FL_solver, s)
Error[180:200]

array([0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.03659961])

In [7]:
A_0

array([[0.6, 0.5, 0.4],
       [0. , 0.4, 0.3],
       [0. , 0. , 0.3]])

In [8]:
10*np.hstack([A_0, B_0])

array([[ 6.,  5.,  4., 10.,  5.],
       [ 0.,  4.,  3.,  5., 10.],
       [ 0.,  0.,  3.,  5.,  5.]])

In [9]:
M = [1, 2, 5, 25, 100]
len(M)

5